{
 "title": "block_device",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_ip",
    "query": "select dev_ip from (select * from block_device order by time desc) as t group by t.dev_ip limit $bd_num;"
   },
   {
    "name": "bd_num",
    "query": "select bd_num from general_info order by time desc limit 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Page In Throughput (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pagein_throughput as value,\n  \"page in throughput\" as metric\nFROM block_device\nWHERE $__timeFilter(time) AND dev_ip = '$device_ip'\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Page Out Throughput (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pageout_throughput as value,\n  \"page out throughput\" as metric\nFROM block_device\nWHERE $__timeFilter(time) AND dev_ip = '$device_ip'\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Page In Latency (microsecond)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pagein_latency as value,\n  \"page in latency\" as metric\nFROM block_device\nWHERE $__timeFilter(time) AND dev_ip = '$device_ip'\nORDER BY time ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  high_pagein_latency as value,\n  \"(90%) page in latency\" as metric\nFROM block_device\nWHERE $__timeFilter(time) AND dev_ip = '$device_ip'\nORDER BY time ASC\n\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  low_pagein_latency as value,\n  \"(10%) page in latency\" as metric\nFROM block_device\nWHERE $__timeFilter(time) AND dev_ip = '$device_ip'\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Page Out Latency (microsecond)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pageout_latency as value,\n  \"page out latency\" as metric\nFROM block_device\nWHERE $__timeFilter(time) AND dev_ip = '$device_ip'\nORDER BY time ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  high_pageout_latency as value,\n  \"(90%) page out latency\" as metric\nFROM block_device\nWHERE $__timeFilter(time) AND dev_ip = '$device_ip'\nORDER BY time ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  low_pageout_latency as value,\n  \"(10%) page out latency\" as metric\nFROM block_device\nWHERE $__timeFilter(time) AND dev_ip = '$device_ip'\nORDER BY time ASC\n\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT FROM_UNIXTIME(UNIX_TIMESTAMP(time)), total_IO, remote_IO, pagein_throughput as IN_TP, pageout_throughput as OUT_TP, pagein_latency as IN_latency, pageout_latency as OUT_latency from block_device;"
    }
   ]
  }
 ]
}